services:
  master-node:
    hostname: master-node
    image: jeff/hadoop
    environment:
      - PGPASSWORD=123456
    extra_hosts:
      - 'master-node:172.20.0.2'
      - 'slave-node:172.20.0.3'
      - 'db-node:172.20.0.5'
    networks:
      my-hadoop:
        ipv4_address: 172.20.0.2
    expose:
      - '20'
    ports:
      - 9870:9870
      - 9864:9864
    tty: true
    stdin_open: true
  
  slave-node:
    hostname: slave-node
    image: jeff/hadoop
    environment:
      - PGPASSWORD=123456
    extra_hosts:
      - 'master-node:172.20.0.2'
      - 'slave-node:172.20.0.3'
      - 'db-node:172.20.0.5'
    networks:
      my-hadoop:
        ipv4_address: 172.20.0.3
    # privileged: true
    expose:
      - '20'
      - '20230'
      - '20231'
    ports:
      - 8088:8088
      - 8081:8081
      - 9000:9000
      - 8083:8083
      - 8042:8042
      - 20230:20230
      - 20231:20231
    tty: true
    stdin_open: true

  # mysql-node:
  #   hostname: mysql-node
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   extra_hosts:
  #     - 'master-node:172.20.0.2'
  #     - 'slave-node:172.20.0.3'
  #     - 'mysql-node:172.20.0.4'
  #     - 'db-node:172.20.0.5'
  #   networks:
  #     my-hadoop:
  #       ipv4_address: 172.20.0.4
  #   expose:
  #     - '20'
  #     - '3306'

  db-node:
    hostname: db-node
    # image: arm64v8/postgres:12.15-bookworm
    image: jeff/hadoop
    environment:
      - PGPASSWORD=123456
    extra_hosts:
      - 'master-node:172.20.0.2'
      - 'slave-node:172.20.0.3'
      - 'db-node:172.20.0.5'
    networks:
      my-hadoop:
        ipv4_address: 172.20.0.5
    expose:
      - '20'
      - '5432'
      - '3306'
    ports:
      - 5432:5432
      - 3306:3306
    tty: true
    stdin_open: true

networks:
  my-hadoop:
    external: true